### PR TITLE
inertial tensor for hallow sphere with unit testing

### PR DESCRIPTION
**Pull request by rleontie**
Inertial tensor matrix function and dumb unit test for it

---
This change is [Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1)

### CODE REVIEW

**Review by edrumwri — CHANGES_REQUESTED** [review]
I'm going to base my feedback on a MATLAB style guide (https://sites.google.com/site/matlabstyleguidelines/).

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-:-LTTPAVl-vrtAmUHK_6U:b-tx9rig)* status: all files reviewed, 6 unresolved discussions (waiting on @rleontie)

___
*[getHallowSphereInertiaTensor.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTVeKv0mkGV6V8GcpP:-LTTVeKv0mkGV6V8GcpQ:b-9ew3xe) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/700280c40f21b8bbfc232a0c5f9f53f28c331616/getHallowSphereInertiaTensor.m#L1)):*
> ```objc
> function I = getHallowSphereInertiaTensor(m,r)
> ```

Nit "I" is typically used to represent an identity matrix. Recommend "J". I also recommend using an underscore to indicate which frame "J" is expressed in. J_0 would indicate the global frame. J_B might indicate the body frame.
___
*[getHallowSphereInertiaTensor.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTVshDCssvaBOrEogn:-LTTVshDCssvaBOrEogo:bk1q6rl) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/700280c40f21b8bbfc232a0c5f9f53f28c331616/getHallowSphereInertiaTensor.m#L1)):*
> ```objc
> function I = getHallowSphereInertiaTensor(m,r)
> ```

Nit "Hallow" -> "Hollow" here and below.
___
*[getHallowSphereInertiaTensor.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTWHuAEIFqPrDoX7CZ:-LTTWHuAEIFqPrDoX7C_:b-bf6ghr) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/700280c40f21b8bbfc232a0c5f9f53f28c331616/getHallowSphereInertiaTensor.m#L1)):*
> ```objc
> function I = getHallowSphereInertiaTensor(m,r)
> ```

From https://sites.google.com/site/matlabstyleguidelines/naming-conventions/variables, `m` and `r` should be spelled out. `mass` and `sphere_radius` are good candidates.
___
*[getHallowSphereInertiaTensor.m, line 5 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTVz8S1wGeMnSgjpxw:-LTTVz8T9aoTFwmtuPzx:ba9hv6h) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/700280c40f21b8bbfc232a0c5f9f53f28c331616/getHallowSphereInertiaTensor.m#L5)):*
> ```objc
> %a 3D hallow sphere of mass m and radius r
> 
> I = diag([2/3*m*r^2, 2/3*m*r^2, 2/3*m*r^2]);
> ```

The repetition here is error prone. Recommend eye(3) * 2/3 * m * r^2.
___
*[TestHallowSphereInertiaTensor.m, line 3 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTW_Ou9qZs1g04arxn:-LTTW_Ou9qZs1g04arxo:bjc2908) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/700280c40f21b8bbfc232a0c5f9f53f28c331616/TestHallowSphereInertiaTensor.m#L3)):*
> ```objc
> classdef TestHallowSphereInertiaTensor < matlab.unittest.TestCase
>     %TestHallowSphereInertiaTensor Unit testing for getHallowSphereInertiaTensor
>     %   Detailed explanation goes here
> ```

"Detailed explanation goes here" should be replaced with what functionality you're testing _exactly_.
___
*[TestHallowSphereInertiaTensor.m, line 10 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTWVkw9mo9xn5Z-fwh:-LTTWVkw9mo9xn5Z-fwi:b-jodx6n) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/700280c40f21b8bbfc232a0c5f9f53f28c331616/TestHallowSphereInertiaTensor.m#L10)):*
> ```objc
>     methods (Test)
>         function dumTest(testCase)
>             m = randi(10,1,1);
> ```

We never do random values in unit tests. They're not repeatable.

**Comment by rleontie** [comment]
all requested changes have been made

**Review by edrumwri — COMMENTED** [review]
Please respond to all of my comments below, if just to say "Done."  This is the Reviewable process.

> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-:-LTTeIT28V7t-GUopaZ3:b-uc9ca9)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @rleontie)

**Review by edrumwri — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1)* status: all files reviewed, 12 unresolved discussions (waiting on @rleontie)

___
*[getHollowSphereInertiaTensor.m, line 1 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTghzACBMOrSh8riLy:-LTTghzACBMOrSh8riLz:bj6qblr) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/cdbeb12a0245c5d4f760f77aa0563b14e7f47252/getHollowSphereInertiaTensor.m#L1)):*
> ```objc
> function J_B = getHollowSphereInertiaTensor(mass,sphere_radius)
> ```

Nit please put spaces after commas (https://sites.google.com/site/matlabstyleguidelines/layout-documentation/white-space)
___
*[getHollowSphereInertiaTensor.m, line 1 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTgvEz7shjJbgjRMPw:-LTTgvF-82jftt1MDbMx:b-gqmx5y) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/cdbeb12a0245c5d4f760f77aa0563b14e7f47252/getHollowSphereInertiaTensor.m#L1)):*
> ```objc
> function J_B = getHollowSphereInertiaTensor(mass,sphere_radius)
> ```

BTW I'm not going to request you change the function name to the style listed in the style guide. I like yours better.
___
*[getHollowSphereInertiaTensor.m, line 2 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTh2QG8P-zG-cCjhT4:-LTTh2QG8P-zG-cCjhT5:b8d75de) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/cdbeb12a0245c5d4f760f77aa0563b14e7f47252/getHollowSphereInertiaTensor.m#L2)):*
> ```objc
> function J_B = getHollowSphereInertiaTensor(mass,sphere_radius)
> %getHollowSphereInertiaTensor function that defines the inertia tensor for
> ```

Nit please put a space after % in comments.
___
*[getHollowSphereInertiaTensor.m, line 5 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTThCYN8Y6udmwAR1l5:-LTThCYN8Y6udmwAR1l6:byvxf3s) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/cdbeb12a0245c5d4f760f77aa0563b14e7f47252/getHollowSphereInertiaTensor.m#L5)):*
> ```objc
> %a 3D hollow sphere of mass "mass" and radius sphere_radius
> 
> J_B = diag([2/3 * mass * sphere_radius^2, 2/3 * mass * sphere_radius^2, 2/3 * mass * sphere_radius^2]);
> ```

You didn't address my issue with repetition here.
___
*[TestHollowSphereInertiaTensor.m, line 2 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTThT8f99WlMyKVEGdP:-LTThJWF5VBgaw2bBuWE:b2k7buk) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/cdbeb12a0245c5d4f760f77aa0563b14e7f47252/TestHollowSphereInertiaTensor.m#L2)):*
> ```objc
> classdef TestHollowSphereInertiaTensor < matlab.unittest.TestCase
>     %TestHollowSphereInertiaTensor Unit testing for getHollowSphereInertiaTensor
> ```

Nit please put a space after % in comments
___
*[TestHollowSphereInertiaTensor.m, line 3 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTThPhj3OwPnfQJTy7x:-LTThPhj3OwPnfQJTy7y:b590xof) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/cdbeb12a0245c5d4f760f77aa0563b14e7f47252/TestHollowSphereInertiaTensor.m#L3)):*
> ```objc
> classdef TestHollowSphereInertiaTensor < matlab.unittest.TestCase
>     %TestHollowSphereInertiaTensor Unit testing for getHollowSphereInertiaTensor
>     %   this runs a sanity test, the hollow Sphere Inertia matrix has a
> ```

nit Neither "Sphere" nor "Inertia" should be capitalized.
___
*[TestHollowSphereInertiaTensor.m, line 14 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTThfAr31McXdunKfi9:-LTThfAr31McXdunKfiA:bo2kyq0) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/cdbeb12a0245c5d4f760f77aa0563b14e7f47252/TestHollowSphereInertiaTensor.m#L14)):*
> ```objc
>             mass = 10;
>             sphere_radius = 1;
>             actSol = getHollowSphereInertiaTensor(mass,sphere_radius);
> ```

Please put a space after commas in function arguments.

**Comment by rleontie** [comment]
I've wrote all my replies but Reviewable doesn't publish the comments (even if I do them one by one or all using the Publish button). It is trying to publish for the last 20+ minutes

**Review by rleontie — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-:-LTTfEGh2uDfjSgTiHZX:b-896fjx)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @edrumwri)

___
*[getHollowSphereInertiaTensor.m, line 1 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTgvEz7shjJbgjRMPw:-LTTjFJ985J6twSHa67j:b-hj6fxl) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/cdbeb12a0245c5d4f760f77aa0563b14e7f47252/getHollowSphereInertiaTensor.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW I'm not going to request you change the function name to the style listed in the style guide. I like yours better.
</blockquote></details>

:) good 
___
*[getHollowSphereInertiaTensor.m, line 2 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTh2QG8P-zG-cCjhT4:-LTTjNEf1eKf88tkEmVz:bb6un1j) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/cdbeb12a0245c5d4f760f77aa0563b14e7f47252/getHollowSphereInertiaTensor.m#L2)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Nit please put a space after % in comments.
</blockquote></details>

Done
___
*[getHollowSphereInertiaTensor.m, line 5 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTThCYN8Y6udmwAR1l5:-LTTjnXG-4UHSFMWRkWs:b-fueve0) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/cdbeb12a0245c5d4f760f77aa0563b14e7f47252/getHollowSphereInertiaTensor.m#L5)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You didn't address my issue with repetition here.
</blockquote></details>

It didn't commit for some reason... Done
___
*[TestHollowSphereInertiaTensor.m, line 14 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTThfAr31McXdunKfi9:-LTTk8bx9kk-WCcHlE4G:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/cdbeb12a0245c5d4f760f77aa0563b14e7f47252/TestHollowSphereInertiaTensor.m#L14)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Please put a space after commas in function arguments.
</blockquote></details>

Done.
___
*[getHallowSphereInertiaTensor.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTVeKv0mkGV6V8GcpP:-LTTf3mh39mzgGA2amwa:b-ne3wpz) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/700280c40f21b8bbfc232a0c5f9f53f28c331616/getHallowSphereInertiaTensor.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Nit "I" is typically used to represent an identity matrix. Recommend "J". I also recommend using an underscore to indicate which frame "J" is expressed in. J_0 would indicate the global frame. J_B might indicate the body frame.
</blockquote></details>

changed this to J_B
___
*[getHallowSphereInertiaTensor.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTVshDCssvaBOrEogn:-LTTenjWBCteB9Ta0FUZ:bn3i0vx) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/700280c40f21b8bbfc232a0c5f9f53f28c331616/getHallowSphereInertiaTensor.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Nit "Hallow" -> "Hollow" here and below.
</blockquote></details>

replaced in the name of the functions and comments everywhere. Files names changed too
___
*[getHallowSphereInertiaTensor.m, line 1 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTWHuAEIFqPrDoX7CZ:-LTTejAo3Dfa5z4AqUlG:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/700280c40f21b8bbfc232a0c5f9f53f28c331616/getHallowSphereInertiaTensor.m#L1)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

From https://sites.google.com/site/matlabstyleguidelines/naming-conventions/variables, `m` and `r` should be spelled out. `mass` and `sphere_radius` are good candidates.
</blockquote></details>

Done.
___
*[getHallowSphereInertiaTensor.m, line 5 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTVz8S1wGeMnSgjpxw:-LTTdOlT8rIPIQGu16LG:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/700280c40f21b8bbfc232a0c5f9f53f28c331616/getHallowSphereInertiaTensor.m#L5)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

The repetition here is error prone. Recommend eye(3) * 2/3 * m * r^2.
</blockquote></details>

Done.
___
*[TestHallowSphereInertiaTensor.m, line 3 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTW_Ou9qZs1g04arxn:-LTTdUAg9cX0JrJuo5gB:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/700280c40f21b8bbfc232a0c5f9f53f28c331616/TestHallowSphereInertiaTensor.m#L3)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

"Detailed explanation goes here" should be replaced with what functionality you're testing _exactly_.
</blockquote></details>

Done.
___
*[TestHallowSphereInertiaTensor.m, line 10 at r1](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTWVkw9mo9xn5Z-fwh:-LTTdTp1B3YhF0sAryJt:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/700280c40f21b8bbfc232a0c5f9f53f28c331616/TestHallowSphereInertiaTensor.m#L10)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

We never do random values in unit tests. They're not repeatable.
</blockquote></details>

Done.

**Review by rleontie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @edrumwri)

___
*[getHollowSphereInertiaTensor.m, line 5 at r2](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTThCYN8Y6udmwAR1l5:-LTTniaI69X-yodaIX7I:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/cdbeb12a0245c5d4f760f77aa0563b14e7f47252/getHollowSphereInertiaTensor.m#L5)):*
<details><summary><i>Previously, rleontie (Roxana Leontie) wrote…</i></summary><blockquote>

It didn't commit for some reason... Done
</blockquote></details>

Done.

**Review by edrumwri — CHANGES_REQUESTED** [review]
Almost there. Forgive the pedantic nature of these comments- they're serving to train you to what I expect.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-:-LTTqwE54bhAu9rL7bkb:b-jrtgj5)* status: all files reviewed, 2 unresolved discussions (waiting on @rleontie)

___
*[getHollowSphereInertiaTensor.m, line 5 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTpqlo5kkbNbcnHd5l:-LTTpqlo5kkbNbcnHd5m:b3oq2no) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/6dfcfe427a6528e8e35551e6534a8d58ddd7db65/getHollowSphereInertiaTensor.m#L5)):*
> ```objc
> % a 3D hollow sphere of mass "mass" and radius "sphere_radius"
> 
> J_B = eye(3)* 2/3 * mass * sphere_radius^2;
> ```

Please put a space between all operators (between eye(3) and the multiplier).
___
*[TestHollowSphereInertiaTensor.m, line 11 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTqpvC8wrBwLrk3Wsq:-LTTqpvD0KjeNoaop19c:b-5euyjs) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/6dfcfe427a6528e8e35551e6534a8d58ddd7db65/TestHollowSphereInertiaTensor.m#L11)):*
> ```objc
>     methods (Test)
>         function sanityTest(testCase)
>             %since this is a closed form solution
> ```

Please put a *single* space between % and the comment that follows.

**Review by rleontie — COMMENTED** [review]
I get it! All valid point though... setting the expectations for future pull requests

> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-:-LTTrM6y6vkskMlhMA0v:bzszg3)* status: all files reviewed, 2 unresolved discussions (waiting on @rleontie)

**Review by rleontie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @edrumwri)

___
*[getHollowSphereInertiaTensor.m, line 5 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTpqlo5kkbNbcnHd5l:-LTTsV2DBTOXCPJWawhw:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/6dfcfe427a6528e8e35551e6534a8d58ddd7db65/getHollowSphereInertiaTensor.m#L5)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Please put a space between all operators (between eye(3) and the multiplier).
</blockquote></details>

Done.
___
*[TestHollowSphereInertiaTensor.m, line 11 at r3](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-LTTqpvC8wrBwLrk3Wsq:-LTTsXFx5nCkal1ZJ_w9:b-896fix) ([raw file](https://github.com/edrumwri/revolute-joint-parameter-estimation/blob/6dfcfe427a6528e8e35551e6534a8d58ddd7db65/TestHollowSphereInertiaTensor.m#L11)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Please put a *single* space between % and the comment that follows.
</blockquote></details>

Done.

**Review by edrumwri — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/revolute-joint-parameter-estimation/1#-:-LTU-5DGDQJsS9NTunhY:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
